# NumPy (Numerical Python)

NumPy works on **multidimensional homogeneous array objects** and it provides a collection of functions to process those arrays. NumPy is known for the fast numerical computations. Numpy provides a high level syntax and it has a very vibrant ecosystem that interopertes for different application areas. The n-dimensional arrays are known as **ndarray**. ndarray forms the primitive building blocks of numerous python libraries.

# Importing numpy

NumPy is available by default in Colab notebooks. Therefore the library can be invoked directly using the *import* statement

*PS: Follow the instructions on the [Installation section](https://numpy.org/install/) of NumPy to make local installations.*


In [1]:
import numpy as np
print("Loaded", np.__version__, "version of numpy!!!")

Loaded 2.2.2 version of numpy!!!


# Creating NumPy arrays

The basic ndarray is created using the **array** function, which takes any sequence as an input parameter. NumPy arrays can be easily created from lists 


In [2]:
# creating a 1 dimensional array
var1 = np.array([1, 2, 3, 4, 5])

# creating a 2 dimensional array
var2 = np.array([[1, 2, 3, 4, 5],
                 [6, 7, 8, 9, 0]])

print("var1 =", var1)
print("var2 =", var2)

var1 = [1 2 3 4 5]
var2 = [[1 2 3 4 5]
 [6 7 8 9 0]]


In [3]:
# It is also possible to specify the type of the element during array creation
var3 = np.array([1, 2, 3], dtype=np.float32)
print("var3 =", var3)

# Notice the usage of numpy arrays to create another array with a different dtype
var4 = np.array(var3, dtype=np.int32)
print("var4 =", var4)

var5 = np.array(var4, dtype=complex)
print("var5 =", var5)

var3 = [1. 2. 3.]
var4 = [1 2 3]
var5 = [1.+0.j 2.+0.j 3.+0.j]


# Array Properties
The important attributes of the ndarray are

*   shape: Dimensions of the array
*   size: Total number of elements in the array
*   ndim: Number of axes
*   dtype: Type of the elements of the array



In [4]:
print(var1.dtype, '\t', var1.shape, '\t', var1.size, '\t', var1.ndim)
print(var2.dtype, '\t', var2.shape, '\t', var2.size, '\t', var2.ndim)
print(var3.dtype, '\t', var3.shape, '\t', var3.size, '\t', var3.ndim)
print(var4.dtype, '\t', var4.shape, '\t', var4.size, '\t', var4.ndim)
print(var5.dtype, '\t', var5.shape, '\t', var5.size, '\t', var5.ndim)

int64 	 (5,) 	 5 	 1
int64 	 (2, 5) 	 10 	 2
float32 	 (3,) 	 3 	 1
int32 	 (3,) 	 3 	 1
complex128 	 (3,) 	 3 	 1


# Other array creation methods

It is not always necessary to have the elements defined during the creation of the arrays. There are several NumPy functions that allows you to create arrays to act as placeholders before the actual computations.

**Exercise #01:**

*   Create different array objects using the following functions: (1) zeros, (2) ones, (3) empty, (4) zeros_like, (5) ones_like, (6) empty_like 


In [12]:
# Solution
array1 = np.zeros((2,3), dtype= "int")
print(f"array zeros = {array1}")

array2 = np.ones((1,8), dtype= "float32")
print(f"array ones = {array2}")

array3 = np.empty((3,2), dtype="str")
print(f"array empty = {array3}")

array4 = np.zeros_like(array2)
print(f"array like array2 with zeros= {array4}")

array5 = np.ones_like(array1)
print(f"array like array1 with ones= {array5}")

array6 = np.empty_like(array1)
print(f"Empty array like array1 = {array6}")

array7 = np.empty_like(array2)
print(f"Empty array like array2 = {array7}")





array zeros = [[0 0 0]
 [0 0 0]]
array ones = [[1. 1. 1. 1. 1. 1. 1. 1.]]
array empty = [['' '']
 ['' '']
 ['' '']]
array like array2 with zeros= [[0. 0. 0. 0. 0. 0. 0. 0.]]
array like array1 with ones= [[1 1 1]
 [1 1 1]]
Empty array like array1 = [[1 1 1]
 [1 1 1]]
Empty array like array2 = [[0. 0. 0. 0. 0. 0. 0. 0.]]


**Exercise #02:**

*   What is the difference between **empty** and **zeros** methods?
*   What is the use of **arange** and **linspace** functions?



**Solution**

Unlike other array creation functions (e.g. zeros_like, ones_like, full_like), empty_like does not initialize the values of the array, and may therefore be marginally faster. However, the values stored in the newly allocated array are arbitrary. For reproducible behavior, be sure to set each element of the array before reading.

Range is  used to easily create a range of values. This function takes three arguments: `start`, `stop`, and `step`, and it returns an array of values starting from `start`, up to (but not including) `stop`, with increments of `step`.

Linspace function is a versatile tool for creating sequences of evenly spaced values within a specified interval. It allows to define a start point and an end point for a given range and determine the total number of evenly spaced values you want within that interval. Importantly, this sequence includes both the start and end points.


# Shape Manipulations

In [27]:
# Creating a numpy array using arrange function
var6 = np.arange(10, dtype=int)
print(var6)

# Reshaping the array into 2 x 5 array
var6 = var6.reshape(2,5)
print(var6)

# Reshaping the array in 3 dimensions
var6 = var6.reshape(1,2,5)
print(var6)

# Note that it is not always necessary to give all three dimensions
var6 = var6.reshape(2, 5,-1)
print(var6)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[[0 1 2 3 4]
  [5 6 7 8 9]]]
[[[0]
  [1]
  [2]
  [3]
  [4]]

 [[5]
  [6]
  [7]
  [8]
  [9]]]


**Exercise #03:**

*   What is the difference between reshape and resize methods?



**Solution**

The `reshape()` method in NumPy changes the shape of an array without modifying its data and returns a new array with the specified shape. In contrast, the `resize()` method can modify the array's data, either in place or by returning a new array, and adjusts the array's shape according to the specified dimensions, filling new elements with repeated copies if necessary.

...

# Indexing, Slicing and Iterating

Indexing and slicing is similar to python lists. We use the **[ ]** operator for providing slices and indices.

In [29]:
var7 = np.array([1, 2, 3, 4, 5])

# indexing the second element
# Remember array indices start with 0 in numpy
print(var7[1])

# slicing the first two elements of the array
print(var7[0:2])

2
[1 2]


In [30]:
# it is also possible to slice arrays based on a condition
print(var7[var7 % 2 == 0])  # prints all the even numbers in the array

[2 4]


In [31]:
var8 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(var8)

# indexing the element at second row and second column
print(var8[1,1])

# it is possible to slice the entire row or column
print(var8[1])
print(var8[:,1])

# slice a particular range
print(var8[0:2, 0:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5
[4 5 6]
[2 5 8]
[[1 2]
 [4 5]]


In [34]:
print(var8[:,2])

[3 6 9]


A visual illustration of slicing mechanism can be seen here

![numpy_indexing.png](https://education-team-2020.s3.eu-west-1.amazonaws.com/ds-ai/indexing-and-slicing.png)

*Reference: https://lectures.scientific-python.org/intro/numpy/array_object.html#indexing-and-slicing*

**Exercise #04:**

*   What is the use of non-zero function? Provide an example of how non-zero function can be used.




**Solution**

*(Double-click or enter to edit)*
The nonzero() function is used to return the indices of the elements in an array that are non-zero. This can be useful for finding the positions of non-zero elements in an array. It returns a tuple of arrays, one for each dimension of the input array, containing the indices of the non-zero elements.
...

In [38]:
# solution
var_non_zeros = np.array([[1, 0, 3], [0, 5, 6], [7, 8, 0]])
non_zero_indexes = np.nonzero(var_non_zeros)
non_zero_indexes

(array([0, 0, 1, 1, 2, 2]), array([0, 2, 1, 2, 0, 1]))

Iterating an array can be either performed using the python list style or using the nditer function.

In [39]:
var9 = np.array([[1, 2, 3], [4, 5, 6]])

for i in var9: # outer loop to access row
    print(i) # returns the entire row

for i in var9: # outer loop to access row
    for j in i:  # iterating each element of the row
        print(j) # returns the element value

[1 2 3]
[4 5 6]
1
2
3
4
5
6


In [40]:
# an alternative to the nesting for loop is the nditer function
var10 = np.array([[1, 2, 3], [4, 5, 6]])
for i in np.nditer(var10):
    print(i)

1
2
3
4
5
6


**Exercise #05:**

*   How can we enumerate a numpy array?



**Solution**

*(Double-click or enter to edit)*

To enumerate a NumPy array, you can use the numpy.ndenumerate() function, which returns an iterator that yields pairs of index and value for each element in the array.
...

It has to be noted that, slices share memory with original array. 

In the below example, var12 is created by slicing var11. Notice the change in var11 after modifying var12.

In [41]:
var11 = np.array([1, 2, 3])

var12 = var11[0:1]

print('before changing:', var11)
var12[0] = 4
print('after changing:', var11)

before changing: [1 2 3]
after changing: [4 2 3]


This leaves us with the question of how the array copy works in numpy

# Array Copy

When you create a new array using the '=' operator, no new copy of the array is created, ie, only a name is created but it refers to the same object.

In [42]:
var13 = np.array([1, 2, 3, 4, 5])

var14 = var13
print('Before modifying', var13)

var14[0] += 1
print('After modifying', var13)

Before modifying [1 2 3 4 5]
After modifying [2 2 3 4 5]


When a view function is used to create a copy of the array, or when the array is sliced, the returned array is only a shallow copy of the original array, ie, an array object is created but the object points to the same data

In [43]:
var15 = np.array([1, 2, 3, 4, 5])

var16 = var15.view()
print('Before modifying (using view)', var15)

var16[0] += 1
print('After modifying (using view)', var15)

var17 = var15[0:3]
print('Before modifying (using slice)', var15)

var17[2] += 1
print('After modifying (using slice)', var15)

Before modifying (using view) [1 2 3 4 5]
After modifying (using view) [2 2 3 4 5]
Before modifying (using slice) [2 2 3 4 5]
After modifying (using slice) [2 2 4 4 5]


To create a deep copy of the array, it is necessary to use the copy method

In [44]:
var18 = np.array([1, 2, 3, 4, 5])

var19 = var18.copy()
print('Before modifying (using copy)', var18)

var19[0] += 1
print('After modifying (using copy)', var18)

Before modifying (using copy) [1 2 3 4 5]
After modifying (using copy) [1 2 3 4 5]


# Adding new axis

It is also possible to increase the dimensions of a numpy array. **np.newaxis** and **expand_dims** can be used to increase the dimensions of the array. This would be used very handy in building convolutional neural networks where you would need to have uniform channel lengths *(will be used in the later exercises)*.

In [45]:
var20 = np.array([1, 2, 3, 4, 5])
print(var20.shape)

a = var20[np.newaxis, :]  # adding new axis to the first axis
print(a.shape)

b = a[np.newaxis, :]  # adding new axis to the first axis
print(b.shape)

c = np.expand_dims(var20, axis=1)  # adding new axis to the second axis
print(c.shape)

d = np.expand_dims(var20, axis=0)  # adding new axis to the first axis
print(d.shape)

(5,)
(1, 5)
(1, 1, 5)
(5, 1)
(1, 5)


# Broadcasting Rules

Broadcasting deals with how numpy treats arrays with different sizes during arithmetic operations. In general, the smaller arrays are broadcasted into the larger array shapes so that both the arrays are compatible.

Read [basic broadcasting rules](https://numpy.org/doc/stable/user/basics.broadcasting.html) for basic knowledge about broadcasting.
Also read [Array broadcasting](https://numpy.org/doc/stable/user/theory.broadcasting.html#array-broadcasting-in-numpy).


In [47]:
var20 = np.array([[1.2, 2.3, 4.0],
                  [1.2, 3.4, 5.2],
                  [0.0, 1.0, 1.3],
                  [0.0, 1.0, 2e-1]])

print(var20)

print(var20 * 2)  # multiplying each element with 2

print(var20 + [1, 0, 1])  # multiplying each row with [1, 0, 1]]

[[1.2 2.3 4. ]
 [1.2 3.4 5.2]
 [0.  1.  1.3]
 [0.  1.  0.2]]
[[ 2.4  4.6  8. ]
 [ 2.4  6.8 10.4]
 [ 0.   2.   2.6]
 [ 0.   2.   0.4]]
[[2.2 2.3 5. ]
 [2.2 3.4 6.2]
 [1.  1.  2.3]
 [1.  1.  1.2]]


**Exercise #06:**

Normalizing values is an important area in any image processing and machine learning problem. In this exercise, we will try to apply normalization at different axis to understand the role of broadcasting.

In [67]:
var21 = np.array([[1.2, 2.3, 4.0],
                  [1.2, 3.4, 5.2],
                  [0.0, 1.0, 1.3],
                  [0.0, 1.0, 2e-1]])

# compute row wise mean
var21_mean = np.round(np.mean(var21, axis=1, keepdims=True), 2)                   # code fill up
print(var21_mean)
print()

# compute column wise mean
var21_mean_clm = np.round(np.mean(var21, axis = 0, keepdims=True), 2)                # code fill up
print(var21_mean_clm)
print()

# do row wise mean subtraction and column wise mean subtraction
# solution

row_wise_sub = np.round(var21 - var21_mean, 2)
print(row_wise_sub)
print()

column_wis_sub = var21  - var21_mean_clm
print(column_wis_sub)


# how do we normalize the entire array using the global mean?

# solution




[[2.5 ]
 [3.27]
 [0.77]
 [0.4 ]]

[[0.6  1.92 2.68]]

[[-1.3  -0.2   1.5 ]
 [-2.07  0.13  1.93]
 [-0.77  0.23  0.53]
 [-0.4   0.6  -0.2 ]]

[[ 0.6   0.38  1.32]
 [ 0.6   1.48  2.52]
 [-0.6  -0.92 -1.38]
 [-0.6  -0.92 -2.48]]




*   Can you think of an example of row wise normalization and column wise normalization?



**Solution**

*(Double-click or enter to edit)*

...

In [68]:
var22 = np.array([[10, 22, 30],
                  [35, 46, 17],
                  [28, 15, 70],
                  [16, 30, 25]])

var23 = np.ones_like(var22)

var24 = var22 - var23

print(var24)

[[ 9 21 29]
 [34 45 16]
 [27 14 69]
 [15 29 24]]




*   Can you think of an example of row wise normalization and column wise normalization?





---


**It has to be noted that this is not a complete tutorial covering the complete numpy aspects. This is provided as an introduction to numpy and its ease of use in numerical computation.**